### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by heiheihei-ops** [linchuming/FFCVSR#2]
您好，我看论文里对于training dataset的描述是你们自己做的，可是github里又写到用的是REDS，请问训练用的数据到底是啥呢，期待您的回复谢谢！
![image](https://user-images.githubusercontent.com/66516707/101308166-30c53080-3884-11eb-8d25-0a16c34e65dd.png)

**Comment by linchuming** [comment]
AAAI里的论文效果是自己采集的，数据量且不方便上传。后续我们改进的带motion的方案采用了REDS作为训练集，具体可以看README。
